[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "3de435b5cc93d1ce0e73233dca57eaa3f42841c3fc76f349f11274cb695fe06"
client_id = "985077610080-u3ml16p73ia6kg7q4mempcntqcfbo2eh.apps.googleusercontent.com"
client_secret = "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"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"


